// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWGuOfQ7leeTUD5sTncbPGpG3bQz11UiE',
    appId: '1:61495515319:web:f3bce504c947f9f9d25532',
    messagingSenderId: '61495515319',
    projectId: 'denisondiningapp',
    authDomain: 'denisondiningapp.firebaseapp.com',
    storageBucket: 'denisondiningapp.appspot.com',
    measurementId: 'G-7ELH094CPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfJ4R4YtBEioD90D6TgJOwqw0M39-4JHk',
    appId: '1:61495515319:android:ab85d884b50c6ab7d25532',
    messagingSenderId: '61495515319',
    projectId: 'denisondiningapp',
    storageBucket: 'denisondiningapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHy9Nf8DEKbM4qBiIxIxZsqhpIp7XRpu8',
    appId: '1:61495515319:ios:e71373d0625802d7d25532',
    messagingSenderId: '61495515319',
    projectId: 'denisondiningapp',
    storageBucket: 'denisondiningapp.appspot.com',
    iosClientId: '61495515319-cuvg4bu3tfud2slg7i024k8vmrjk35t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.denisonDiningApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHy9Nf8DEKbM4qBiIxIxZsqhpIp7XRpu8',
    appId: '1:61495515319:ios:e71373d0625802d7d25532',
    messagingSenderId: '61495515319',
    projectId: 'denisondiningapp',
    storageBucket: 'denisondiningapp.appspot.com',
    iosClientId: '61495515319-cuvg4bu3tfud2slg7i024k8vmrjk35t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.denisonDiningApp2',
  );
}
